# Sử dụng hình ảnh chính thức của ASP.NET Core runtime làm hình ảnh cơ sở
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Sử dụng hình ảnh chính thức của SDK ASP.NET Core để xây dựng ứng dụng
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["WebBanHang/WebBanHang.csproj", "WebBanHang/"]
RUN dotnet restore "WebBanHang/WebBanHang.csproj"
COPY . .
WORKDIR "/src/WebBanHang"
RUN dotnet build "WebBanHang.csproj" -c Release -o /app/build

# Publish ứng dụng
FROM build AS publish
RUN dotnet publish "WebBanHang.csproj" -c Release -o /app/publish

# Chạy ứng dụng
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebBanHang.dll"]